CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520232911_AddUsuario') THEN
    CREATE TABLE "Usuarios" (
        "UsuarioId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" text NOT NULL,
        "Email" text NOT NULL,
        "Senha" text NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("UsuarioId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520232911_AddUsuario') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260520232911_AddUsuario', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260521005842_AddCategorias') THEN
    CREATE TABLE "Categorias" (
        "CategoriaId" integer GENERATED BY DEFAULT AS IDENTITY,
        "NomeCategoria" text NOT NULL,
        CONSTRAINT "PK_Categorias" PRIMARY KEY ("CategoriaId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260521005842_AddCategorias') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260521005842_AddCategorias', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522015727_AddProduto') THEN
    ALTER TABLE "Categorias" ADD "ProdutoId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522015727_AddProduto') THEN
    CREATE TABLE "Produtos" (
        "ProdutoId" integer GENERATED BY DEFAULT AS IDENTITY,
        "NomeProduto" text NOT NULL,
        "Descricao" text,
        "ImagemUrls" text[] NOT NULL,
        "Quantidade" integer NOT NULL,
        "Tamanho" integer NOT NULL,
        "ValorCompra" numeric NOT NULL,
        "ValorVenda" numeric NOT NULL,
        "Ativo" boolean NOT NULL,
        CONSTRAINT "PK_Produtos" PRIMARY KEY ("ProdutoId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522015727_AddProduto') THEN
    CREATE INDEX "IX_Categorias_ProdutoId" ON "Categorias" ("ProdutoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522015727_AddProduto') THEN
    ALTER TABLE "Categorias" ADD CONSTRAINT "FK_Categorias_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produtos" ("ProdutoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522015727_AddProduto') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522015727_AddProduto', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522021141_AddVenda') THEN
    CREATE TABLE "Vendas" (
        "VendaId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ValorVenda" numeric,
        "DataVenda" timestamp with time zone,
        CONSTRAINT "PK_Vendas" PRIMARY KEY ("VendaId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522021141_AddVenda') THEN
    CREATE TABLE "VendaItens" (
        "VendaItemId" integer GENERATED BY DEFAULT AS IDENTITY,
        "VendaId" integer NOT NULL,
        "ProdutoId" integer NOT NULL,
        "QuantidadeItem" integer NOT NULL,
        "ValorItem" numeric,
        CONSTRAINT "PK_VendaItens" PRIMARY KEY ("VendaItemId"),
        CONSTRAINT "FK_VendaItens_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produtos" ("ProdutoId") ON DELETE CASCADE,
        CONSTRAINT "FK_VendaItens_Vendas_VendaId" FOREIGN KEY ("VendaId") REFERENCES "Vendas" ("VendaId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522021141_AddVenda') THEN
    CREATE INDEX "IX_VendaItens_ProdutoId" ON "VendaItens" ("ProdutoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522021141_AddVenda') THEN
    CREATE INDEX "IX_VendaItens_VendaId" ON "VendaItens" ("VendaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522021141_AddVenda') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522021141_AddVenda', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522022232_AddEstoque') THEN
    CREATE TABLE "EntradasEstoque" (
        "EstoqueId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProdutoId" integer NOT NULL,
        "QuantidadeEntrada" integer NOT NULL,
        "DataEntrada" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EntradasEstoque" PRIMARY KEY ("EstoqueId"),
        CONSTRAINT "FK_EntradasEstoque_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produtos" ("ProdutoId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522022232_AddEstoque') THEN
    CREATE INDEX "IX_EntradasEstoque_ProdutoId" ON "EntradasEstoque" ("ProdutoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522022232_AddEstoque') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522022232_AddEstoque', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522024837_AddDespesa') THEN
    CREATE TABLE "Despesas" (
        "DespesaId" integer GENERATED BY DEFAULT AS IDENTITY,
        "NomeDespesa" text NOT NULL,
        CONSTRAINT "PK_Despesas" PRIMARY KEY ("DespesaId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522024837_AddDespesa') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522024837_AddDespesa', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260523014036_AddContaAPagar') THEN
    CREATE TABLE "ContasAPagar" (
        "ContaAPagarId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ContaId" integer NOT NULL,
        "DespesaId" integer NOT NULL,
        "NumeroParcela" integer NOT NULL,
        "TotalParcelas" integer NOT NULL,
        "ValorParcela" numeric NOT NULL,
        "ValorTotal" numeric NOT NULL,
        "DataVencimento" timestamp with time zone NOT NULL,
        "DataAbertura" timestamp with time zone NOT NULL,
        "DataPagamento" timestamp with time zone,
        "Pago" boolean NOT NULL,
        CONSTRAINT "PK_ContasAPagar" PRIMARY KEY ("ContaAPagarId"),
        CONSTRAINT "FK_ContasAPagar_Despesas_DespesaId" FOREIGN KEY ("DespesaId") REFERENCES "Despesas" ("DespesaId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260523014036_AddContaAPagar') THEN
    CREATE INDEX "IX_ContasAPagar_DespesaId" ON "ContasAPagar" ("DespesaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260523014036_AddContaAPagar') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260523014036_AddContaAPagar', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524021939_AddDestaqueField') THEN
    ALTER TABLE "Produtos" ADD "Destaque" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524021939_AddDestaqueField') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260524021939_AddDestaqueField', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524024641_AddProdutoEstoque') THEN
    ALTER TABLE "Produtos" DROP COLUMN "Quantidade";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524024641_AddProdutoEstoque') THEN
    ALTER TABLE "Produtos" DROP COLUMN "Tamanho";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524024641_AddProdutoEstoque') THEN
    ALTER TABLE "VendaItens" ADD "Tamanho" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524024641_AddProdutoEstoque') THEN
    ALTER TABLE "EntradasEstoque" ADD "Tamanho" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524024641_AddProdutoEstoque') THEN
    CREATE TABLE "ProdutoEstoques" (
        "ProdutoEstoqueId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProdutoId" integer NOT NULL,
        "Tamanho" integer NOT NULL,
        "Quantidade" integer NOT NULL,
        CONSTRAINT "PK_ProdutoEstoques" PRIMARY KEY ("ProdutoEstoqueId"),
        CONSTRAINT "FK_ProdutoEstoques_Produtos_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produtos" ("ProdutoId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524024641_AddProdutoEstoque') THEN
    CREATE INDEX "IX_ProdutoEstoques_ProdutoId" ON "ProdutoEstoques" ("ProdutoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524024641_AddProdutoEstoque') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260524024641_AddProdutoEstoque', '8.0.27');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524181337_AddProdutoCategoriasManyToMany') THEN
    ALTER TABLE "Categorias" DROP CONSTRAINT "FK_Categorias_Produtos_ProdutoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524181337_AddProdutoCategoriasManyToMany') THEN
    DROP INDEX "IX_Categorias_ProdutoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524181337_AddProdutoCategoriasManyToMany') THEN
    ALTER TABLE "Categorias" DROP COLUMN "ProdutoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524181337_AddProdutoCategoriasManyToMany') THEN
    CREATE TABLE "ProdutoCategorias" (
        "CategoriasCategoriaId" integer NOT NULL,
        "ProdutosProdutoId" integer NOT NULL,
        CONSTRAINT "PK_ProdutoCategorias" PRIMARY KEY ("CategoriasCategoriaId", "ProdutosProdutoId"),
        CONSTRAINT "FK_ProdutoCategorias_Categorias_CategoriasCategoriaId" FOREIGN KEY ("CategoriasCategoriaId") REFERENCES "Categorias" ("CategoriaId") ON DELETE CASCADE,
        CONSTRAINT "FK_ProdutoCategorias_Produtos_ProdutosProdutoId" FOREIGN KEY ("ProdutosProdutoId") REFERENCES "Produtos" ("ProdutoId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524181337_AddProdutoCategoriasManyToMany') THEN
    CREATE INDEX "IX_ProdutoCategorias_ProdutosProdutoId" ON "ProdutoCategorias" ("ProdutosProdutoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524181337_AddProdutoCategoriasManyToMany') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260524181337_AddProdutoCategoriasManyToMany', '8.0.27');
    END IF;
END $EF$;
COMMIT;

